import './globals.css'
import { Inter  as FontSans} from 'next/font/google'

import { ModeToggle } from "~/components/Toggle";
import { ThemeProvider } from "~/components/theme-provider";
import { Toaster } from "~/components/ui/sonner";
import { cn } from "~/lib/utils";
import Header from "~/components/Header";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={``} suppressHydrationWarning>
      <body
        className={cn("min-h-screen font-sans antialiased", fontSans.variable)}
      >
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}{" "}
          <div className="fixed bottom-4 right-4 z-50">
            <ModeToggle />
          </div>{" "}
          <Toaster theme="system"  toastOptions={{
    classNames: {
      toast: "bg-gray-900 text-white border border-gray-700",
      title: "font-bold",
      description: "text-gray-300",
      actionButton: "bg-indigo-600 hover:bg-indigo-700",
      cancelButton: "bg-gray-600 hover:bg-gray-700"
    }
  }}/>
        </ThemeProvider>
      </body>
    </html>
  )
}
